# Generated by Django 5.1.3 on 2024-11-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_company_city_company_state_alter_company_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='locality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
