services:
  django:
    build:
      context: ./catalyst-count
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env.backend

    volumes:
      - ./catalyst-count:/app
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    container_name: my_postgres
    env_file:
      - .env.db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis-server
    ports:
      - "6379:6379"

  celery:
    build:
      context: ./catalyst-count
    container_name: celery_worker
    command: celery -A catalyst_count.celery worker --loglevel=info
    depends_on:
      - redis
    env_file:
      - .env.backend
    volumes:
      - ./catalyst-count:/app

volumes:
  postgres_data:
